### ISSUE TITLE
lab6 docker-compose (only for p3 and p4)

### ISSUE THREAD

**Issue by Zyber404** [byrzhm/hadoop-docker-cluster#2]
```yaml
services:
  xxx-2021211xxx-1:
    image: lab6
    container_name: xxx-2021211xxx-1
    hostname: xxx-2021211xxx-1 # TODO: Change this to name-SID-1
    ports:
      - "8081:8081" 
      - "9870:9870" 
      - "8088:8088" 
      - "8020:8020" 
      - "16010:16010"
    command: bash -c "
              service ssh restart && 
              inithosts.sh 1 &&
              zkServer.sh start &&
              tail -f /dev/null"
              # hdfs namenode -format &&
              # start-all.sh &&
    network_mode: "bridge"
    

  xxx-2021211xxx-2:
    image: lab6
    container_name: xxx-2021211xxx-2
    hostname: xxx-2021211xxx-2 # TODO: Change this to name-SID-2
    command: bash -c "
              service ssh restart && 
              inithosts.sh 2 &&
              zkServer.sh start &&
              tail -f /dev/null"
    network_mode: "bridge"
    depends_on:
      - xxx-2021211xxx-1

  xxx-2021211xxx-3:
    image: lab6
    container_name: xxx-2021211xxx-3
    hostname: xxx-2021211xxx-3 # TODO: Change this to name-SID-3
    command: bash -c "
              service ssh restart && 
              inithosts.sh 3 && 
              zkServer.sh start &&
              tail -f /dev/null"
    network_mode: "bridge"
    depends_on:
      - xxx-2021211xxx-1
      - xxx-2021211xxx-2

  xxx-2021211xxx-4:
    image: lab6
    container_name: xxx-2021211xxx-4
    hostname: xxx-2021211xxx-4 # TODO: Change this to name-SID-4
    command: bash -c "
              service ssh restart && 
              inithosts.sh 4 && 
              zkServer.sh start &&
              tail -f /dev/null"
    network_mode: "bridge"
    depends_on:
      - xxx-2021211xxx-1
      - xxx-2021211xxx-2
      - xxx-2021211xxx-3
```
